#!/usr/bin/env bash
# Create PID file, run infinite loop and handle signals

echo "$$" > /tmp/myscript.pid

trap 'echo "I hate the kill command"; rm -f /tmp/myscript.pid; exit' SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
